name: Slack Product Review Notifier

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: |
      contains(github.event.pull_request.labels.*.name, 'need product review') &&
      !contains(github.event.pull_request.labels.*.name, 'wip')
    runs-on: ubuntu-latest

    steps:
    # Uncomment this to see available github properties
    # - name: Dump GitHub context
    #   id: github_context_step
    #   run: echo '${{ toJSON(github) }}'

    - uses: actions/checkout@v2
    - name: Notify Slack
      run: |
        curl -X POST \
        -H 'Content-type: application/json' \
        --data '{
          "text": "A new PR is available for product review",
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "${{ github.event.pull_request.title }}"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "A new PR is available for product review"
              }
            },
            {
              "type": "actions",
              "block_id": "actions1",
              "elements": [
                {
                  "type": "button",
                  "action_id": "view_pr",
                  "text": {
                    "type": "plain_text",
                    "text": "View PR"
                  },
                  "url": "${{ github.event.pull_request.html_url }}"
                }
              ]
            }
          ]
        }' \
        ${{ secrets.SLACK_WEBHOOK }}
